# Generated by Django 5.0.1 on 2024-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=254)),
                ('image_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('content', models.CharField(max_length=254)),
            ],
        ),
    ]
